### ISSUE TITLE
Display logo in sticky menu

### ISSUE THREAD

**Issue by JamesAM** [tsquez/wp-forge#24]
For a new site I'm building, I'd like to display the logo in the sticky menu, once that menu has stuck to the top.

I've had a look in content-nav.php and attempted to modify part of it by copying the logo call to it, but that ended up displaying two logos in the header when the sticky menu was not stuck.

What would be the best way to include the logo in that menu? Thanks.

**Comment by tsquez** [comment]
Since we have moved this over to email, I am going to close this amigo.
