### ISSUE TITLE
Wordpress problem reveal foundation

### ISSUE THREAD

**Issue by iamericlarson** [tsquez/wp-forge#26]
Thomas or anyone else..Could you please let me know what I am doing wrong.

http://www.wpromotions.net

1) link at top right of header with a pop up modal using reveal
2) doesn’t work..could jQuery mess this all up?

any help would be much appreciated!

**Comment by baringji** [comment]
The modal is working. Its just that when clicking the space above your navigation/menu that modal displays.

**Comment by tsquez** [comment]
Hi Eric,

I did look at your site yesterday but it was on my phone and like baringji stated, the pop up was working. I did notice that the hamburger icon did cover that modal link.

I think you have changed the site to another theme so I can't take a look at it on my desktop.

**Comment by tsquez** [comment]
I haven't heard if you got this taken care of or not, so I am going to close the issue. If you need to please reopen.
