### ISSUE TITLE
Foundation sticky offcanvas not working with foundationpress theme

### ISSUE THREAD

**Issue by vani89** [tsquez/wp-forge#29]
This is my site. http://fspb.valse.com.my/

my CSS

.off-canvas-fixed {
    -webkit-transition: -webkit-transform 500ms ease;
    transition: transform 500ms ease;
  
    
    
    
}
.move-right > .off-canvas-fixed {
    -webkit-transform: translate3d(15.625rem, 0, 0);
    transform: translate3d(15.625rem, 0, 0);
    height:100%;
    
}
.left-off-canvas-menu {
    -webkit-transform: none;
    transform: none;
    margin-left: -15.625rem;
    height: 100%;
    
}
.main-section {
    padding:45px 0 0;
    
}
.tab-bar {
    width:100%;
   
}
@media only screen and (orientation:landscape) and (max-width: 64em){
    .main-section {
        padding:0 0 0 2.8125rem;
    }
    .off-canvas-fixed {
        width:2.8125rem;
        height:100%;
        background:#333333;
    }
     section.left-small{
        border:none;
        box-shadow:none;
    }
}

my HTML

<div class="off-canvas-wrap">
    <div class="fixed off-canvas-fixed hide-for-large-up"> <a class="exit-off-canvas"></a>

        <nav class="tab-bar">
            <section class="left-small"> <a class="left-off-canvas-toggle menu-icon" href="#"><span></span></a>

            </section>
            <section class="show-for-portrait right tab-bar-section">
                 <h1 class="title">Logo</h1>

            </section>
        </nav>
        <aside class="left-off-canvas-menu">
            <ul class="off-canvas-list">
                <li class="show-for-small">
                      
                    </li>
                    <li><a href="index.php">home</a></li>
      		    	<li><a href="productlisting.php" class="selected">product</a></li>
      		    	<li><a href="">help</a></li>
      		    	
      		    	<li><a href="">contact</a></li>
      		    	<li><a href="">login/sign up</a></li>
            </ul>
        </aside>
    </div>
    <div class="inner-wrap"> <a class="exit-off-canvas"></a>
    	
    	</div>
 </div>

It works perfectly with just Foundation 5. When used in Foundationpress theme (foundation + Wordpress) it doesn't work . I mean the menu is not showing up but the title remains sticky.

**Comment by tsquez** [comment]
vani89,
I thought that you were talking about a site built with WP-Forge, not a site built with another WordPress/Foundation theme. I only provide assistance to people who use my theme WP-Forge. My apologies for misunderstanding. I will close this.
