### ISSUE TITLE
Customizer for .contain-to-grid background-color

### ISSUE THREAD

**Issue by badcat** [tsquez/wp-forge#36]
Wish there was a way in the WP Customizer to alter the background color on ".contain-to-grid" so the menu background is in better keeping with the color work done on the menu items.  Note the defaults of the #333333 grey/black 
![containtogrid](https://cloud.githubusercontent.com/assets/26096/6642114/9299b3fc-c978-11e4-807f-f221c9e8ddd4.png)

**Comment by badcat** [comment]
Well - not sure if this passes the muster, but I added this to functions;
```
    // Nav Stickygrid Background Color   @ line 135
  $wp_customize->add_setting('contain_to_grid_color', array(
    'default' => '#333333',
    'type' => 'theme_mod',
    'capability' => 'manage_options',
    'sanitize_callback' => 'sanitize_hex_color',
    'priority' => 5,    
  ));
  $wp_customize->add_control(new WP_Customize_Color_Control($wp_customize,'contain_to_grid_color',array(
    'label' => __('Select Container Background Color', 'wpforge'),
    'section' => 'nav_content',
    'settings' => 'contain_to_grid_color',
  )));

  //  @line 1173
.contain-to-grid{background:<?php echo get_theme_mod('contain_to_grid_color','#333333'); ?>;}
```
Seems to work even with Child Themes.

**Comment by tsquez** [comment]
@badcat thanks for bringing this to my attention. 

Good work on the customizer code as well, works as it should. However you do not need to add all of that code to make the `.contain-to-grid` element follow the same color you set for the top-bar.

All you have to do is open up customizer.php, scroll all the way down to the following function `function wpforge_customize_css()` and look for the following declaration (should come right after nav_wrap):

`.top-bar,.top-bar-section ul li,.top-bar-section li:not(.has-form) a:not(.button),.top-bar-section ul li:hover:not(.has-form) > a,.top-bar-section .dropdown li:not(.has-form):not(.active) > a:not(.button)`

and add `contain-to-grid` at the very end, like this:

`.top-bar,.top-bar-section ul li,.top-bar-section li:not(.has-form) a:not(.button),.top-bar-section ul li:hover:not(.has-form) > a,.top-bar-section .dropdown li:not(.has-form):not(.active) > a:not(.button),.containt-to-grid`

You will notice that the `.contain-to-grid` element will now take on the same color as the top-bar.

Now if you want the `.contain-to-grid` element to have a different color then yes you would use the code you created above. Hope this helps and again thank you for bringing this to my attention. I will make sure it makes it into the next version of WP-Forge.

**Comment by badcat** [comment]
Hah! Yep that's certainly more elegant. 
Thanks. Will update mine in the meanwhile.

**Comment by tsquez** [comment]
Just wanted you to know that I did add it to the next version of WP-Forge which is 5.5.1.8 - the latest version waiting for final admin approval is 5.5.1.7
