### ISSUE TITLE
Main Menu - Contain to grid sticky does not work in Firefox 36.0

### ISSUE THREAD

**Issue by philsniff** [tsquez/wp-forge#38]
Hello ,
i like the theme very, but the option for the sticke menu in the topbar doesn't work in newer firefox.
when ich scroll down, the navigation scrolls up. now when i refresh the page without scrolling to the top, the navigation comes as a sticky nac. also the top-button in the lower right of the page. and now it works.

but when you comes first to the page, the script ist not working.

in ie, chrome it works very well.

edit: sorry, after closing Firefox and restart it works all fine. sorry :-)

**Comment by badcat** [comment]
Seems to work here on Firefox 36.0.1 Mac

**Comment by philsniff** [comment]
yes here windows 7 firefox 36.0.1 too after restart,
i wish the sticky nav wouldt work in mobilview either. so that the mobile nav is also fixed on the top.
