### ISSUE TITLE
@since WP-Forge Version numbering.

### ISSUE THREAD

**Issue by baringji** [tsquez/wp-forge#41]
Hey Thomas,

Would it be nice to retain the `@since WP-Forge #.#.#` of the files if there were no updates on the code? Given the statement it says - since - so it should follow where it started/created. The history of the file also will be retain.

I don't know how this affects in Wordpress.org though.

**Comment by tsquez** [comment]
Sure I think we can do that moving forward.

**Comment by tsquez** [comment]
Ooops sorry hit the wrong button
