### ISSUE TITLE
Topbar user breakpoint for toggle

### ISSUE THREAD

**Issue by badcat** [tsquez/wp-forge#42]
Feature Request - Would love have a customizer option to allow a user breakpoint to toggle the Foundation topbar. 

http://foundation.zurb.com/forum/posts/1053-changing-topbar-breakpoint-using-css

**Comment by tsquez** [comment]
Very interesting and a very solid request. I will def look into this for you. I think this would go over rather nicely with all the users :wink:

**Comment by badcat** [comment]
Yep - I hoped it could tie in nicely with your options to change the section container widths. Not sure what I can offer code-wise, but I'm here for feedback and testing :)

**Comment by tsquez** [comment]
I think so as well. I have had some users inquire into it a few times. I
just simply forgot about it...Lol

Hopefully if all goes well I can get it in for 5.5.1.9 as that will be the
final version as we wait for F6.

And to answer you're question, yes I will be supporting F6, how soon after
it's released is left to be determined....Lol. We will just have to wait
and see what happens :wink:

via my phone

**Comment by kim07** [comment]
:+1:

**Comment by szabeszg** [comment]
Hi Thomas,
+1  I use !important to override the rules baked in, but that is not a proper solution either (and I'm missing sass badly in these cases...). End user type clients should not be able to access the customizer anyway, except when we want them to ruin the design...
Hope you can come up with a solution.

**Comment by marvinsss2005** [comment]
Hi,

Im using this http://foundation.zurb.com/forum/posts/1053-changing-topbar-breakpoint-using-css and set the break point to 64.0625em and the break point mobile menu works but when my width is above 40.0625em the toggle mobile menu dropdown is not functioning, any ideas?

**Comment by tsquez** [comment]
Hi you just have to play with the different widths. Remember there are
different media queries for different devices. Look at the very bottom of
the style sheet of WP-Forge and you will see what I mean

via my phone

**Comment by marvinsss2005** [comment]
Hi,

I changed these defulat lines from foundation.css...

line 1692 meta.foundation-mq-topbar {
  font-family: "/only screen and (min-width:40.0625em)/";
  width: 40.0625em; }

line 2038 @media only screen and (min-width: 40.0625em) {
  .top-bar {

to...

line 1692 meta.foundation-mq-topbar {
  font-family: "/only screen and (min-width:50.0625em)/";
  width: 40.0625em; }

line 2038 @media only screen and (min-width: 50.0625em) {
  .top-bar {

The width is working but when i click the top-bar mobile it is not working, the nav links does not show up.

I tried modifying the bottom style.css media queries but still not working.
@media only screen and (min-width: 40.063em) and (max-width: 64em) { }
@media only screen and (min-width: 64.063em) and (max-width: 90em) { }
@media only screen and (min-width: 90.063em) and (max-width: 120em)

**Comment by tsquez** [comment]
Hey there I was looking at this yesterday for another user and I cam up with something. I did this long ago for a client. What I did was I opened content-off_canvas.php and I did the following on line 17. I changed this:

`<nav class="tab-bar show-for-small-only">` to this `<nav class="tab-bar show-for-medium-down">` Now the off canvas menu shows on anything smaller than 1024.

Is this what you were going for? Please let me know.
