### ISSUE TITLE
Footer nav only positions in the center

### ISSUE THREAD

**Issue by JamesAM** [tsquez/wp-forge#43]
Hi there,

I'm not sure the customizer is working with regard to the nav menu in the footer. 

Whether the setting in the customizer is set to align the nav menu to the left or right, it only ever appears in the center (in a 12 column row).

The text aligns left or right just fine though.

**Comment by tsquez** [comment]
I will def take a look at it when I get home amigo, thanks for the heads up.

via my phone

**Comment by tsquez** [comment]
Yep James you are correct. This will be fixed with the 5.5.2 update coming out soon. It will take me a few days.

I am rolling back to 5.5.1.7 and starting from there. Seems a few things went wrong in 5.5.1.8 and I cannot understand why.

**Comment by JamesAM** [comment]
Sorry to be the bearer of bad news. Pesky gremlins!

**Comment by tsquez** [comment]
Bring the bad news, that's how we are going to keep the theme the best she
can be. By all means if you spot something let me know

via my phone
