### ISSUE TITLE
Sidebar container misslabled class in style.css

### ISSUE THREAD

**Issue by marzels** [tsquez/wp-forge#44]
Hi there,

while trying to make the background transparent (currently using a "solution" that requires !important) I found out that in the style.css the class for the footer-sidebar is labled **.footer_sidebar-container** which caused the problem that changes for all containers had no effect on the sidebar. So I took a look into the sidebar-footer.php and there the class was called **sidebar_container** like the other containers.

**Comment by tsquez** [comment]
Thank you, this will be corrected in WP-FORGE 5.5.2.

via my phone
