### ISSUE TITLE
customizer error

### ISSUE THREAD

**Issue by gabbyy** [tsquez/wp-forge#47]
this error message show in customizer "Warning: Creating default object from empty value in /home/ghmode04/public_html/wp-content/themes/wp-forge/inc/customizer.php on line 61" making it impossible to save chages. using wordpress 4.3

**Comment by tsquez** [comment]
Hi there,

So can you give a little more information please. This release had been out since last week and no other users have reported anything like this.

Were you doing something, changing something? More information would be helpful to assist with this.

Thank you.

**Comment by tsquez** [comment]
Nevermind I see what happened. They changed some of the values of the customizer in WordPress 4.3 - this is what is causing the error message to appear. Working on the correction now.

My apologies, I didn't know they were changing it that much.

**Comment by tsquez** [comment]
https://wordpress.org/support/topic/error-in-customizer-after-updating-to-wordpress-43?replies=1

**Comment by gabbyy** [comment]
Thanks,
works perfect now.
I'm a big fan though

**Comment by tsquez** [comment]
Good glad it worked. I released the 5.5.2.5 update and thankfully the
review team pushed it through.

I see another update coming soon though. I need to rearrange the customizer.

Thanks for being a fan of the theme, if possible please leave a rating and
a review, if you haven't fine do already.

Add always, enjoy!

via my phone
