### ISSUE TITLE
contain-to-grid menu option

### ISSUE THREAD

**Issue by HenkBarreveld** [tsquez/wp-forge#49]
`contain-to-grid.js` offers a nice and simple way, together with some styling, to make the topbar (`div.contain-to-grid`) sticky.

However, I think it will be better to replace
`jQuery(window).on(scroll function() {`
by something like
`jQuery(window).on('load scroll resize orientationChange', function () {`
to cover other actions, in addition to `scroll` that could influence the position of the topbar.

As it is now, a window reload while the topbar is fixed, will cause the topbar to disappear.

**Comment by tsquez** [comment]
I am really not sure what you are referring to when you say

> _As it is now, a window reload while the topbar is fixed, will cause the topbar to disappear._

I've never experienced that. Could you provide me with a screenshot or a link to an example?

Thanks again.

**Comment by HenkBarreveld** [comment]
Hello Thomas,
No problem, here is an example: [video](http://urbino.nl/videos/wpforge-topbar.avi)

This is what I did:
- Open a website that uses the WP-Forge theme
- Scroll down until the topbar (menu bar) is fixed
- Reload the page; the topbar disappears
- Resize the page: no topbar
- Scroll up a little: the topbar is back!

**Comment by tsquez** [comment]
OK I tried what you said and I see what you are referring to, however where do you see the following:

`jQuery(window).on(scroll function() {`

it isn't in `contain-to-grid.js` and it isn't in any of the theme files of WP-Forge. Could you be a little more specific as to where you saw this? That would be very helpful. 

Thanks again.

**Comment by tsquez** [comment]
Nevermind, I found it, well not exactly it...lol...I was looking for the exact phrase you referenced, but it is in `contain-to-grid-sticky.js` and I added your suggestion and it works like a charm 😃 

I'll make this part of the next update. Thanks again amigo for the suggestion Great work 👍

**Comment by HenkBarreveld** [comment]
Hello Thomas,
I was indeed referring to `jQuery(window).scroll(function() {` in the file contain-to-grid.js; not `jQuery(window).on(scroll function() {` (which would not even work :-))
Sorry for the confusion!
