### ISSUE TITLE
Top-Bar Link Active Color

### ISSUE THREAD

**Issue by ottopotto** [tsquez/wp-forge#50]
Hi,

there's currently a customizer color option "Top-Bar Active Color" but no "Top-Bar Link Active Color" that would set the `color` of `.menu .active > a`.

For example a black top bar background and white link color together with white active link background hides the text of the active link.

Could the color option "Top-Bar Link Active Color" be added? (For my purposes "Top-Bar Link Hover Color" could be reused to set the color of `.menu .active > a` but I imagine that these two should be separated in some cases.)

**Comment by tsquez** [comment]
Hey there,

Def this can be done amigo and I have been wanting to do this for a while now but I keep forgetting.

I'll make this part of the next update. Thanks again for mentioning it. Its greatly appreciated.

**Comment by tsquez** [comment]
Almost done with the 6.3 update, I hope to have this included in the update. Stay tuned. Thanks again for the input.

**Comment by tsquez** [comment]
Actually, removing Foundation `active` class from WP-Forge. I have opted to go with the built in `current-menu-item` that is built into WordPress. This is easier to style and looks a lot cleaner. See this post https://developer.wordpress.org/reference/functions/wp_nav_menu/

I think it looks great and I hope you do to :wink:

**Comment by ottopotto** [comment]
Sounds good. Thank you!
