### ISSUE TITLE
Foundation CSS Settings

### ISSUE THREAD

**Issue by smith-daniels** [tsquez/wp-forge#52]
It appears the latest release uses the new XY Grid system in Foundations 6.4 however, this is not reflected under the "Foundation CSS Settings" customize section.

**Comment by tsquez** [comment]
Hi there,

Not sure what you are referring to as there is no "Foundation CSS Settings" customize section in WP-Forge.

**Comment by tsquez** [comment]
My apologies I take that back, sorry I forgot about that section and yes you are correct. I just woke up and literally haven't had my coffee yet...lol

I was planning on adding all three available to that area but I am not sure this would do any good for anyone as they would still have to make changes from rows and columns to grids and cells.

There may be a way to do that however. Thank you very much, you have just given me an idea....lol

**Comment by smith-daniels** [comment]
Glad I could help!
